version: "3"
services:

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis:/data
    network_mode: host
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  spring-eureka:
    image: bernardjason/spring-eureka
    network_mode: host
    ports:
      - "1111:1111"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]

  spring-edge-controller:
    image: bernardjason/spring-edge-controller
    network_mode: host
    ports:
      - "3333:3333" 
      - "3344:3344"
    depends_on:
      - redis
      - spring-eureka
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]

  play-tracker:
    image: bernardjason/play-tracker
    network_mode: host
    ports:
      - "9000:9000" 
    depends_on:
      - spring-edge-controller
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  python-tracker:
    image: bernardjason/python-tracker
    network_mode: host
    volumes:
      - ./db:/home/app/db
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]


volumes:
  db:
