#!/bin/bash

logs=/var/log
if [ -f /usr/local/lib/spring-edge-tracker-0.1-SNAPSHOT.jar ] ; then
	exec java -jar /usr/local/lib/spring-edge-tracker-0.1-SNAPSHOT.jar $* --server user-control > ${logs}/user-control.log 2>&1 &
	exec java -jar /usr/local/lib/spring-edge-tracker-0.1-SNAPSHOT.jar $* --server ticket-control > ${logs}/ticket-control.log 2>&1  
else
	exec java -jar target/spring-edge-tracker-0.1-SNAPSHOT.jar $* -s user-control &
	echo $! > pid2
	exec java -jar target/spring-edge-tracker-0.1-SNAPSHOT.jar $* -s ticket-control  &
	echo $! > pid1
fi
